@Configuration
public class RabbitMQConfig {

    @Bean
    public DirectExchange bookExchange() {
        return new DirectExchange("bookExchange");
    }

    @Bean
    public Queue bookQueue() {
        return new Queue("bookQueue");
    }

    @Bean
    public Binding binding(Queue bookQueue, DirectExchange bookExchange) {
        return BindingBuilder.bind(bookQueue).to(bookExchange).with("bookRoutingKey");
    }


}
